### ISSUE TITLE
Generalizing keywords

### ISSUE THREAD

**Issue by dpny518** [mindorii/kws#2]
How would you use librispeech and commonvoice to train? would you just update 
"data/train.json" with the transcripts and file names and duration from those two database

Then once it is trained, how would you keyword spot for new words for example if I want the word mindorii, i would just record maybe ~100 samples of it? and how to adapt it and use it?

 kws = models.KWS(args.save_path, "mindorii",window_size=800, step_size=200
like that?

Thank you

**Comment by chrislengerich** [comment]
Just change the file paths in the JSON and make sure the files referenced are the right format.

We mix target keyword and LV corpus during training.  You may need more than 100 samples (our sample keywords have about 1500 total).

That looks like the right invocation for testing.

**Comment by dpny518** [comment]
awesome
